#!/usr/bin/env ruby

# check if production install
if __FILE__.start_with?('/sbin/')
  UTILS_PATH='/usr/share/katello'
else
  UTILS_PATH=File.expand_path('..', __FILE__)
end

require File.join(UTILS_PATH, 'hostname-change.rb')

hostname_change = KatelloUtilities::HostnameChange.new("Foreman Proxy", "Foreman Proxies", "foreman-proxy-content")

if hostname_change.accepted_scenarios.include? hostname_change.last_scenario
  hostname_change.run
else
  STDOUT.puts hostname_change.error_message
end
